version: '3.8'

services:
  api:
    build:
      context: /home/ricardo/Documentos/Particular/APsiC/APsiOpcDaApi
      dockerfile: Dockerfile
    container_name: apsic_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=apsic_postgres;Port=5432;Database=APsiOpcDaApiDb;Username=postgres;Password=Teste2010
    depends_on:
      - postgres  # Define que a API depende do serviço do PostgreSQL
    ports:
      - "5000:5000"
    restart: always

  postgres:
    image: postgres:latest
    container_name: apsic_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teste2010
      - POSTGRES_DB=APsiOpcDaApiDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # Caminho para o script de inicialização
    ports:
      - "5434:5432"  # Porta externa 5434, interna 5432
    restart: always

volumes:
  postgres_data:

